apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: board-postgres-pvc
  namespace: board
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
      