apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-fe
  namespace: board
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: board-fe
  template:
    metadata:
      labels:
        app: board-fe
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: board-fe
          image: minheek/missions:fe-k3s
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
         