apiVersion: v1
kind: PersistenceVolumeClaim
metadata:
  name: board-postgres-primary-pvc
  namespace: board
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

